### PR TITLE
Configure all uris as strings instead of URI parts

### LINKED ISSUE #60: Configure URIs as single strings instead of as scheme/hostname/port/path
To make the authservice a little easier to configure, we could change the configuration format to take URIs as plain old URI strings instead of as structures of scheme/hostname/port/path.

### PR DESCRIPTION
**Pull request by andrewedstrom**
Resolves #60

### CODE REVIEW

**Comment by peterhaochen47** [comment]
@googlebot I fixed it.

**Comment by andrewedstrom** [comment]
@googlebot I fixed it.

**Comment by peterhaochen47** [comment]
@googlebot I fixed it.

**Comment by peterhaochen47** [comment]
@googlebot I fixed it.

**Comment by peterhaochen47** [comment]
@googlebot I fixed it.

**Comment by peterhaochen47** [comment]
Closing this PR due to CLA issue, replaced by PR #77

**Pull request closed without merging**
