### PR TITLE
Remove extraneous whitespace

### PR DESCRIPTION
**Pull request by tylerschultz**

### CODE REVIEW

**Comment by tylerschultz** [comment]
@googlebot I signed it!

**Comment by tylerschultz** [comment]
@googlebot I signed it!

**Comment by EmBerz** [comment]
lgtm

**Comment by EmBerz** [comment]
@googlebot i approve

**Comment by EmBerz** [comment]
@googlebot lgtm

**Comment by tylerschultz** [comment]
@googlebot I approve

**Pull request merged**
