### PR TITLE
http: Ignore X509_R_CERT_ALREADY_IN_HASH_TABLE

### PR DESCRIPTION
**Pull request by dio**
The previous error checking was wrong, since
ctx.add_certificate_authority is already done the ERR_get_error. The relevant SSL error should be wrapped as system::error_code.

Signed-off-by: Dhi Aurrahman <dio@rockybars.com>

### CODE REVIEW

**Comment by dio** [comment]
This supersedes https://github.com/istio-ecosystem/authservice/pull/229 to test the theory presented in: https://github.com/istio-ecosystem/authservice/pull/229#discussion_r1020593895

**Comment by dio** [comment]
@Shikugawa @incfly when you have time, please help to take a look. 🙇🏾

**Review by Shikugawa — APPROVED** [review]
LGTM

**Comment by dio** [comment]
Awesome. Thanks, @Shikugawa 🙇🏾!

**Pull request merged**
